version: '2'
services:
  bookwise:
    container_name: book_wise
    environment:
      VERIFY_TOKEN: "${VERIFY_TOKEN}"
      FB_PAGE_ACCESS_TOKEN: "${FB_PAGE_ACCESS_TOKEN}"
      DB_HOST: db
    build: .
    image: test/book-wise:latest
    command:
      - /bin/sh
      - -c
      - |
        npm install
        node ./index.js
    volumes:
      - .:/app
    ports:
      - "1337:1337"
    depends_on:
      - db
  db:
    container_name: mongodb
    image: mongo
    volumes:
      - mongodb:/data
    ports:
      - "27017:27017"
volumes:
  mongodb: