version: '2'
services:
  bookwise:
    container_name: book_wise
    environment:
      VERIFY_TOKEN: "${VERIFY_TOKEN}"
      FB_PAGE_ACCESS_TOKEN: "${FB_PAGE_ACCESS_TOKEN}"
    build: .
    image: test/book-wise:latest
    command:
      - /bin/sh
      - -c
      - |
        npm install
        node ./index.js
    volumes:
      - .:/app
    ports:
      - "1337:1337"